alumnos/__init__.py
from flask import Blueprint

alumnos = Blueprint('alumnos',
    __name__, template_folder='templates',
    static_folder='static')

from . import routes

alumnos/routes.py
from flask import render_template, request, redirect, url_for
import forms
from models import db, Alumnos
from . import alumnos

@alumnos.route("/", methods=['GET','POST'])
@alumnos.route("/alumnos")
def index():
    create_form = forms.UserForm(request.form)
    alumnos_list = Alumnos.query.all()
    return render_template("alumnos/index.html", form=create_form, alumno=alumnos_list)

@alumnos.route("/alum", methods=['GET', 'POST'])
def alumnos_route():
    create_form = forms.UserForm(request.form)
    if request.method == 'POST':
        alum = Alumnos(nombre=create_form.nombre.data,
                       apellidos=create_form.apellidos.data,
                       email=create_form.email.data,
                       telefono=create_form.telefono.data)
        db.session.add(alum)
        db.session.commit()
        return redirect(url_for('alumnos.index'))
    
    alumnos_list = Alumnos.query.all()
    return render_template("alumnos/Alumnos.html", form=create_form, alumno=alumnos_list)

@alumnos.route("/detalles", methods=['GET', 'POST'])
def detalles():
    id = ""
    nombre = ""
    apellidos = ""
    email = ""
    telefono = ""
    
    if request.method == 'GET':
        id = request.args.get('id')
        if id: 
            alum1 = db.session.query(Alumnos).filter(Alumnos.id == id).first()
            if alum1:
                nombre = alum1.nombre
                apellidos = alum1.apellidos
                email = alum1.email
                telefono = alum1.telefono
                
    return render_template('alumnos/detalles.html', id=id, nombre=nombre, apellidos=apellidos, email=email, telefono=telefono)

@alumnos.route("/modificar", methods=['GET', 'POST'])
def modificar():
    create_form = forms.UserForm(request.form)
    if request.method == 'GET':
        id = request.args.get('id')
        alum1 = db.session.query(Alumnos).filter(Alumnos.id==id).first()
        if alum1:
            create_form.id.data = id
            create_form.nombre.data = alum1.nombre
            create_form.apellidos.data = alum1.apellidos
            create_form.email.data = alum1.email
            create_form.telefono.data = alum1.telefono

    if request.method == 'POST':
        id = request.args.get('id')
        alum1 = db.session.query(Alumnos).filter(Alumnos.id==id).first()
        if alum1:
            alum1.nombre = create_form.nombre.data
            alum1.apellidos = create_form.apellidos.data
            alum1.email = create_form.email.data
            alum1.telefono = create_form.telefono.data
            db.session.commit()
            return redirect(url_for('alumnos.index'))
            
    alumnos_list = Alumnos.query.all()
    return render_template("alumnos/modificar.html", form=create_form, alumno=alumnos_list)

@alumnos.route("/eliminar", methods=['GET', 'POST'])
def eliminar():
    create_form = forms.UserForm(request.form)
    if request.method == 'GET':
        id = request.args.get('id')
        alum1 = db.session.query(Alumnos).filter(Alumnos.id==id).first()
        if alum1:
            create_form.id.data = id
            create_form.nombre.data = alum1.nombre
            create_form.apellidos.data = alum1.apellidos
            create_form.email.data = alum1.email
            create_form.telefono.data = alum1.telefono

    if request.method == 'POST':
        id = create_form.id.data
        alum = Alumnos.query.get(id)
        if alum:
            db.session.delete(alum)
            db.session.commit()
        return redirect(url_for('alumnos.index'))
        
    alumnos_list = Alumnos.query.all()
    return render_template("alumnos/eliminar.html", form=create_form, alumno=alumnos_list)

templates/alumnos/Alumnos.html
{% extends "layout.html" %}

{% block container %}
{% import "_macros.html" as macros %}

<div class="flex items-center justify-center w-full min-h-[70vh]">

    <form method="POST" class="w-full max-w-md mx-auto">
        {{ form.csrf_token }}

        <div class="grid md:grid-cols-2 md:gap-6">

            <div class="relative z-0 w-full mb-5 group">
                {{ macros.camposNuevos(form.nombre, class="block py-2.5 px-0 w-full text-sm text-heading bg-transparent
                border-0 border-b-2 border-default-medium appearance-none focus:outline-none focus:ring-0
                focus:border-brand peer") }}
            </div>

            <div class="relative z-0 w-full mb-5 group">
                {{ macros.camposNuevos(form.apellidos, class="block py-2.5 px-0 w-full text-sm text-heading
                bg-transparent border-0 border-b-2 border-default-medium appearance-none focus:outline-none focus:ring-0
                focus:border-brand peer") }}
            </div>


            <div class="relative z-0 w-full mb-5 group">
                {{ macros.camposNuevos(form.email, class="block py-2.5 px-0 w-full text-sm text-heading bg-transparent
                border-0 border-b-2 border-default-medium appearance-none focus:outline-none focus:ring-0
                focus:border-brand
                peer") }}
            </div>
            <div class="relative z-0 w-full mb-5 group">
                {{ macros.camposNuevos(form.telefono, class="block py-2.5 px-0 w-full text-sm text-heading bg-transparent
                border-0 border-b-2 border-default-medium appearance-none focus:outline-none focus:ring-0
                focus:border-brand
                peer") }}
            </div>


        </div>

        <div class="mt-6">
            <button type="submit"
                class="text-white bg-brand box-border border border-transparent hover:bg-brand-strong focus:ring-4 focus:ring-brand-medium shadow-xs font-medium leading-5 rounded-base text-sm px-4 py-2.5 focus:outline-none">
                Submit
            </button>
        </div>

    </form>

</div>

{% endblock %}

templates/alumnos/detalles.html
{% extends "layout.html" %}

{% block container %}

<div class="flex items-center justify-center w-full min-h-[70vh]">

    <div class="relative bg-neutral-primary-soft max-w-xs w-full p-6 border border-default rounded-base shadow-xs">

        <button id="dropdownButton" data-dropdown-toggle="dropdown"
            class="absolute top-2 end-2 text-body hover:text-heading bg-neutral-primary-soft box-border border border-transparent hover:bg-neutral-tertiary focus:ring-4 focus:ring-neutral-tertiary rounded-base p-1.5 focus:outline-none"
            type="button">
            <span class="sr-only">Open dropdown</span>
            <svg class="w-6 h-6" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" width="24" height="24"
                fill="none" viewBox="0 0 24 24">
                <path stroke="currentColor" stroke-linecap="round" stroke-width="3" d="M6 12h.01m6 0h.01m5.99 0h.01" />
            </svg>
        </button>

        <div id="dropdown"
            class="z-10 bg-neutral-primary-medium border border-default-medium rounded-base shadow-lg w-36 block hidden">
            <ul class="p-2 text-sm text-body font-medium" aria-labelledby="dropdownButton">
                <li><a href="#"
                        class="inline-flex items-center w-full p-2 hover:bg-neutral-tertiary-medium hover:text-heading rounded-md">Edit</a>
                </li>
                <li><a href="#"
                        class="inline-flex items-center w-full p-2 hover:bg-neutral-tertiary-medium hover:text-heading rounded-md">Export
                        Data</a></li>
                <li><a href="#"
                        class="inline-flex items-center w-full p-2 text-fg-danger hover:bg-neutral-tertiary-medium rounded-md">Delete</a>
                </li>
            </ul>
        </div>

        <div class="flex flex-col items-center">
            <img class="w-24 h-24 mb-6 rounded-full" src="img/profile.png" alt="Profile image" />

            <h5 class="mb-0.5 text-xl font-semibold tracking-tight text-heading text-center">
                {{ nombre }} {{ apellidos }}
            </h5>
            <span class="text-sm text-body text-center mt-1">{{ email }}</span>
            <span class="text-sm text-body text-center mt-1">{{ telefono }}</span>

            <div class="flex mt-4 md:mt-6 gap-4">
                <a href="{{ url_for('alumnos.index') }}"
                    class="inline-flex items-center text-white bg-brand box-border border border-transparent hover:bg-brand-strong focus:ring-4 focus:ring-brand-medium shadow-xs font-medium leading-5 rounded-base text-sm px-4 py-2.5 focus:outline-none">
                    Regresar
                </a>
            </div>
        </div>
    </div>

</div>

{% endblock %}

templates/alumnos/eliminar.html
{% extends "layout.html" %}

{% block container %}
{% import "_macros.html" as macros %}

<div class="flex items-center justify-center w-full min-h-[70vh]">

    <form method="POST" class="w-full max-w-md mx-auto">
        {{ form.csrf_token }}

        <div class="relative z-0 w-full mb-5 group">
            {{ macros.camposNuevos(form.id, class="block py-2.5 px-0 w-full text-sm text-heading bg-transparent
            border-0 border-b-2 border-default-medium appearance-none focus:outline-none focus:ring-0
            focus:border-brand peer") }}
        </div>
        <div class="grid md:grid-cols-2 md:gap-6">

            <div class="relative z-0 w-full mb-5 group">
                {{ macros.camposNuevos(form.nombre, class="block py-2.5 px-0 w-full text-sm text-heading bg-transparent
                border-0 border-b-2 border-default-medium appearance-none focus:outline-none focus:ring-0
                focus:border-brand peer") }}
            </div>

            <div class="relative z-0 w-full mb-5 group">
                {{ macros.camposNuevos(form.apellidos, class="block py-2.5 px-0 w-full text-sm text-heading
                bg-transparent border-0 border-b-2 border-default-medium appearance-none focus:outline-none focus:ring-0
                focus:border-brand peer") }}
            </div>

            <div class="relative z-0 w-full mb-5 group">
                {{ macros.camposNuevos(form.email, class="block py-2.5 px-0 w-full text-sm text-heading bg-transparent
                border-0 border-b-2 border-default-medium appearance-none focus:outline-none focus:ring-0
                focus:border-brand
                peer") }}
            </div>
            <div class="relative z-0 w-full mb-5 group">
                {{ macros.camposNuevos(form.telefono, class="block py-2.5 px-0 w-full text-sm text-heading
                bg-transparent
                border-0 border-b-2 border-default-medium appearance-none focus:outline-none focus:ring-0
                focus:border-brand
                peer") }}
            </div>

        </div>

        <div class="mt-6">
            <button type="submit"
                class="text-white bg-brand box-border border border-transparent hover:bg-brand-strong focus:ring-4 focus:ring-brand-medium shadow-xs font-medium leading-5 rounded-base text-sm px-4 py-2.5 focus:outline-none">
                Eliminar
            </button>
        </div>
        <div class="mt-6">
            <a href="{{ url_for('alumnos.index') }}"
                class="inline-block text-white bg-brand box-border border border-transparent hover:bg-brand-strong focus:ring-4 focus:ring-brand-medium shadow-xs font-medium leading-5 rounded-base text-sm px-4 py-2.5 focus:outline-none text-center">
                Cancelar
            </a>
        </div>

    </form>

</div>

{% endblock %}

templates/alumnos/index.html
{% extends "layout.html" %}

{% block container %}

<div class="py-10 relative overflow-x-auto sm:rounded-lg">

    <div class="mb-4">
        <a href="{{ url_for('alumnos.alumnos_route') }}"
            class="inline-flex items-center gap-2 bg-green-500 text-white px-4 py-2 rounded hover:bg-green-600 w-max">
            <svg class="w-6 h-6 text-white" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" width="24" height="24"
                fill="none" viewBox="0 0 24 24">
                <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                    d="M16 12h4m-2 2v-4M4 18v-1a3 3 0 0 1 3-3h4a3 3 0 0 1 3 3v1a1 1 0 0 1-1 1H5a1 1 0 0 1-1-1Zm8-10a3 3 0 1 1-6 0 3 3 0 0 1 6 0Z" />
            </svg>
            Nuevo
        </a>
    </div>

    <table class="w-full text-sm text-left rtl:text-right text-gray-500 dark:text-gray-400">
        <thead class="text-xs text-gray-700 uppercase bg-gray-50 dark:bg-gray-700 dark:text-gray-400">
            <tr>
                <th scope="col" class="px-6 py-3">Nombre</th>
                <th scope="col" class="px-6 py-3">Apellidos</th>
                <th scope="col" class="px-6 py-3">Correo</th>
                <th scope="col" class="px-6 py-3">Teléfono</th>
                <th scope="col" class="px-6 py-3 text-center">Editar</th>
                <th scope="col" class="px-6 py-3 text-center">Detalles</th>
                <th scope="col" class="px-6 py-3 text-center">Eliminar</th>
            </tr>
        </thead>
        <tbody>
            {% for alum in alumno %}
            <tr
                class="bg-white border-b dark:bg-gray-800 dark:border-gray-700 border-gray-200 hover:bg-gray-50 dark:hover:bg-gray-600">

                <td class="px-6 py-4 font-medium text-gray-900 whitespace-nowrap dark:text-white">
                    {{ alum.nombre }}
                </td>
                <td class="px-6 py-4">{{ alum.apellidos }}</td>
                <td class="px-6 py-4">{{ alum.email }}</td>
                <td class="px-6 py-4">{{ alum.telefono }}</td>
                <td class="px-6 py-4">
                    <a href="{{ url_for('alumnos.modificar', id=alum.id) }}"
                        class="flex items-center justify-center gap-2 bg-orange-500 text-white px-3 py-2 rounded hover:bg-orange-600">
                        <svg class="w-5 h-5" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none"
                            viewBox="0 0 24 24">
                            <path stroke="currentColor" stroke-linecap="square" stroke-linejoin="round" stroke-width="2"
                                d="M7 19H5a1 1 0 0 1-1-1v-1a3 3 0 0 1 3-3h1m4-6a3 3 0 1 1-6 0 3 3 0 0 1 6 0Zm7.441 1.559a1.907 1.907 0 0 1 0 2.698l-6.069 6.069L10 19l.674-3.372 6.07-6.07a1.907 1.907 0 0 1 2.697 0Z" />
                        </svg>
                        Editar
                    </a>
                </td>

                <td class="px-6 py-4">
                    <a href="{{ url_for('alumnos.detalles', id=alum.id) }}"
                        class="flex items-center justify-center gap-2 bg-purple-500 text-white px-3 py-2 rounded hover:bg-purple-600">
                        <svg class="w-5 h-5" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor">
                            <path d="M10 2a8 8 0 100 16 8 8 0 000-16zM8.5 11l3-3-3-3 1-1 4 4-4 4-1-1z" />
                        </svg>
                        Detalles
                    </a>
                </td>

                <td class="px-6 py-4">
                    <a href="{{ url_for('alumnos.eliminar', id=alum.id) }}"
                        class="flex items-center justify-center gap-2 bg-red-500 text-white px-3 py-2 rounded hover:bg-red-600">
                        <svg class="w-5 h-5" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none"
                            viewBox="0 0 24 24">
                            <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                                d="M5 7h14m-9 3v8m4-8v8M10 3h4a1 1 0 0 1 1 1v3H9V4a1 1 0 0 1 1-1ZM6 7h12v13a1 1 0 0 1-1 1H7a1 1 0 0 1-1-1V7Z" />
                        </svg>
                        Eliminar
                    </a>
                </td>

            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>

{% endblock %}

templates/alumnos/modificar.html
{% extends "layout.html" %}

{% block container %}
{% import "_macros.html" as macros %}

<div class="flex items-center justify-center w-full min-h-[70vh]">

    <form method="POST" class="w-full max-w-md mx-auto">
        {{ form.csrf_token }}

        <div class="relative z-0 w-full mb-5 group">
            {{ macros.camposNuevos(form.id, class="block py-2.5 px-0 w-full text-sm text-heading bg-transparent
            border-0 border-b-2 border-default-medium appearance-none focus:outline-none focus:ring-0
            focus:border-brand peer") }}
        </div>
        <div class="grid md:grid-cols-2 md:gap-6">

            <div class="relative z-0 w-full mb-5 group">
                {{ macros.camposNuevos(form.nombre, class="block py-2.5 px-0 w-full text-sm text-heading bg-transparent
                border-0 border-b-2 border-default-medium appearance-none focus:outline-none focus:ring-0
                focus:border-brand peer") }}
            </div>

            <div class="relative z-0 w-full mb-5 group">
                {{ macros.camposNuevos(form.apellidos, class="block py-2.5 px-0 w-full text-sm text-heading
                bg-transparent border-0 border-b-2 border-default-medium appearance-none focus:outline-none focus:ring-0
                focus:border-brand peer") }}
            </div>

            <div class="relative z-0 w-full mb-5 group">
                {{ macros.camposNuevos(form.email, class="block py-2.5 px-0 w-full text-sm text-heading bg-transparent
                border-0 border-b-2 border-default-medium appearance-none focus:outline-none focus:ring-0
                focus:border-brand
                peer") }}
            </div>

            <div class="relative z-0 w-full mb-5 group">
                {{ macros.camposNuevos(form.telefono, class="block py-2.5 px-0 w-full text-sm text-heading bg-transparent
                border-0 border-b-2 border-default-medium appearance-none focus:outline-none focus:ring-0
                focus:border-brand
                peer") }}
            </div>

        </div>

        <div class="mt-6">
            <button type="submit"
                class="text-white bg-brand box-border border border-transparent hover:bg-brand-strong focus:ring-4 focus:ring-brand-medium shadow-xs font-medium leading-5 rounded-base text-sm px-4 py-2.5 focus:outline-none">
                Submit
            </button>
        </div>

    </form>

</div>

{% endblock %}